// <auto-generated>
//   This file was generated with Protogen (for Protobuf-net); you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace TikTokLiveSharp.Models
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<Message> Messages { get; } = new global::System.Collections.Generic.List<Message>();

        [global::ProtoBuf.ProtoMember(2, Name = @"cursor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cursor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int fetchInterval { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long serverTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string internalExt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int fetchType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public WebsocketParam wsParam { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int heartbeatDuration { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool needAck { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string wsUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"binary")]
        public byte[] Binary { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebsocketParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"action")]
        public int Action { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastRoomUserSeqMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public int viewerCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"comment")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Comment { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastMemberMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"event")]
        public WebcastMessageEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int actionId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastGiftMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int giftId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int repeatCount { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int repeatEnd { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public WebcastGiftMessageGiftDetails giftDetails { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public WebcastGiftMessageGiftExtra giftExtra { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastGiftMessageGiftExtra : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"timestamp")]
        public ulong Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ulong receiverUserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastGiftMessageGiftDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public WebcastGiftMessageGiftImage giftImage { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string giftName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"describe")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Describe { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        public int giftType { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int diamondCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastGiftMessageGiftImage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string giftPictureUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicBattle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<WebcastLinkMicBattleItems> battleUsers { get; } = new global::System.Collections.Generic.List<WebcastLinkMicBattleItems>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicBattleItems : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public WebcastLinkMicBattleGroup battleGroup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicBattleGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        public LinkUser User { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicArmies : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<WebcastLinkMicArmiesItems> battleItems { get; } = new global::System.Collections.Generic.List<WebcastLinkMicArmiesItems>();

        [global::ProtoBuf.ProtoMember(7)]
        public int battleStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicArmiesItems : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong hostUserId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<WebcastLinkMicArmiesGroup> battleGroups { get; } = new global::System.Collections.Generic.List<WebcastLinkMicArmiesGroup>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLinkMicArmiesGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"users")]
        public global::System.Collections.Generic.List<User> Users { get; } = new global::System.Collections.Generic.List<User>();

        [global::ProtoBuf.ProtoMember(2, Name = @"points")]
        public int Points { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastSocialMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"event")]
        public WebcastMessageEvent Event { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLikeMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"event")]
        public WebcastMessageEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int likeCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int totalLikeCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastQuestionNewMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public QuestionDetails questionDetails { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestionDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string questionText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"user")]
        public User User { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastMessageEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8)]
        public WebcastMessageEventDetails eventDetails { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastMessageEventDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string displayType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class User : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong userId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        public ProfilePicture profilePicture { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public UserExtraAttributes extraAttributes { get; set; }

        [global::ProtoBuf.ProtoMember(38)]
        [global::System.ComponentModel.DefaultValue("")]
        public string uniqueId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(64, Name = @"badges")]
        public global::System.Collections.Generic.List<UserBadgesAttributes> Badges { get; } = new global::System.Collections.Generic.List<UserBadgesAttributes>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LinkUser : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong userId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public ProfilePicture profilePicture { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string uniqueId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProfilePicture : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"urls")]
        public global::System.Collections.Generic.List<string> Urls { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserExtraAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public int followRole { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserBadgesAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(21, Name = @"badges")]
        public global::System.Collections.Generic.List<UserBadge> Badges { get; } = new global::System.Collections.Generic.List<UserBadge>();

        [global::ProtoBuf.ProtoMember(20)]
        public global::System.Collections.Generic.List<UserImageBadge> imageBadges { get; } = new global::System.Collections.Generic.List<UserImageBadge>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserBadge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastWebsocketMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"binary")]
        public byte[] Binary { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastWebsocketAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastLiveIntroMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"user")]
        public User User { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SystemMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastInRoomBannerMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Data { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"colour")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Colour { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"id")]
        public ulong Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WeeklyRanking : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
        public RankItem Rank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankContainer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"rankings")]
        public WeeklyRanking Rankings { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastHourlyRankMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public RankContainer Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserImageBadge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int displayType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"image")]
        public UserImageBadgeImage Image { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserImageBadgeImage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Url { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastEmoteChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"emote")]
        public EmoteDetails Emote { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EmoteDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string emoteId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"image")]
        public EmoteImage Image { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EmoteImage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imageUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WebcastEnvelopeMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public TreasureBoxData treasureBoxData { get; set; }

        [global::ProtoBuf.ProtoMember(1)]
        public TreasureBoxUser treasureBoxUser { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureBoxUser : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"user2")]
        public TreasureBoxUser2 User2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureBoxUser2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"user3")]
        public global::System.Collections.Generic.List<TreasureBoxUser3> User3s { get; } = new global::System.Collections.Generic.List<TreasureBoxUser3>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureBoxUser3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(21, Name = @"user4")]
        public TreasureBoxUser4 User4 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureBoxUser4 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        public User User { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureBoxData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"coins")]
        public uint Coins { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint canOpen { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"timestamp")]
        public ulong Timestamp { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
