// <auto-generated>
//   This file was generated with Json2csharp; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: json
// </auto-generated>

using System.Collections.Generic;

namespace TikTokLiveSharp.Models
{
    public class DefaultFormat
    {
        public bool bold { get; set; }
        public string color { get; set; }
        public int font_size { get; set; }
        public bool italic { get; set; }
        public int italic_angle { get; set; }
        public bool use_heigh_light_color { get; set; }
        public bool use_remote_clor { get; set; }
        public int weight { get; set; }
    }

    public class DisplayText
    {
        public DefaultFormat default_format { get; set; }
        public string default_pattern { get; set; }
        public string key { get; set; }
        public List<object> pieces { get; set; }
    }

    public class GiftLabelIcon
    {
        public string avg_color { get; set; }
        public int height { get; set; }
        public int image_type { get; set; }
        public bool is_animated { get; set; }
        public string open_web_url { get; set; }
        public string uri { get; set; }
        public List<string> url_list { get; set; }
        public int width { get; set; }
    }

    public class GiftPanelBanner
    {
        public List<object> bg_color_values { get; set; }
        public DisplayText display_text { get; set; }
        public LeftIcon left_icon { get; set; }
        public string schema_url { get; set; }
    }

    public class Icon
    {
        public string avg_color { get; set; }
        public int height { get; set; }
        public int image_type { get; set; }
        public bool is_animated { get; set; }
        public string open_web_url { get; set; }
        public string uri { get; set; }
        public List<string> url_list { get; set; }
        public int width { get; set; }
    }

    public class Image
    {
        public string avg_color { get; set; }
        public int height { get; set; }
        public int image_type { get; set; }
        public bool is_animated { get; set; }
        public string open_web_url { get; set; }
        public string uri { get; set; }
        public List<string> url_list { get; set; }
        public int width { get; set; }
    }

    public class LeftIcon
    {
        public string avg_color { get; set; }
        public int height { get; set; }
        public int image_type { get; set; }
        public bool is_animated { get; set; }
        public string open_web_url { get; set; }
        public string uri { get; set; }
        public List<string> url_list { get; set; }
        public int width { get; set; }
    }

    public class LockInfo
    {
        public bool @lock { get; set; }
        public int lock_type { get; set; }
    }

    public class TikTokGift
    {
        public int action_type { get; set; }
        public int app_id { get; set; }
        public string business_text { get; set; }
        public bool can_put_in_gift_box { get; set; }
        public List<object> color_infos { get; set; }
        public bool combo { get; set; }
        public string describe { get; set; }
        public int diamond_count { get; set; }
        public int duration { get; set; }
        public string event_name { get; set; }
        public bool for_custom { get; set; }
        public bool for_linkmic { get; set; }
        public GiftLabelIcon gift_label_icon { get; set; }
        public GiftPanelBanner gift_panel_banner { get; set; }
        public string gift_rank_recommend_info { get; set; }
        public int gift_scene { get; set; }
        public string gold_effect { get; set; }
        public string gray_scheme_url { get; set; }
        public string guide_url { get; set; }
        public Icon icon { get; set; }
        public int id { get; set; }
        public Image image { get; set; }
        public bool is_box_gift { get; set; }
        public bool is_broadcast_gift { get; set; }
        public bool is_displayed_on_panel { get; set; }
        public bool is_effect_befview { get; set; }
        public bool is_gray { get; set; }
        public bool is_random_gift { get; set; }
        public int item_type { get; set; }
        public LockInfo lock_info { get; set; }
        public string manual { get; set; }
        public string name { get; set; }
        public bool notify { get; set; }
        public int primary_effect_id { get; set; }
        public string region { get; set; }
        public string scheme_url { get; set; }
        public SpecialEffects special_effects { get; set; }
        public TrackerParams tracker_params { get; set; }
        public List<object> trigger_words { get; set; }
        public int type { get; set; }
    }

    public class SpecialEffects
    {
    }

    public class TrackerParams
    {
    }
}
